### ISSUE TITLE
delete_from_list.ends_with doesn't seem to be working

### ISSUE THREAD

**Issue by bby-bishopclark** [sous-chefs/line#109]
### Cookbook version
1.0.4 (appears to be missing in 2.0.0 as well, via source inspection)

### Chef-client version
14.1.12

### Platform Details
RHEL 7.5

### Scenario:
```
  ['/etc/default/grub'].each do |f|     # cheap hack to avoid name duplication->typos
    delete_from_list f do
      path      f
      pattern   'GRUB_CMDLINE_LINUX="'
      delim     [' ']
      entry     'elevator=noop'
      ends_with '"'
      #    backup       true    # line >= 2.0.0 only
      only_if File.exist?(f)
    end
  end
```

### Steps to Reproduce:
as above

### Expected Result:

```
--- /dev/fd63       2018-05-30 16:01:16.715879150 -0700
+++ /etc/default/grub   2018-05-31 09:41:52.100677036 -0700
@@ -2,5 +2,5 @@
 GRUB_DEFAULT=saved
 GRUB_DISABLE_SUBMENU=true
 GRUB_TERMINAL_OUTPUT="console"
-GRUB_CMDLINE_LINUX="rd.lvm.lv=centos/root rd.lvm.lv=centos/swap crashkernel=auto rhgb net.ifnames=0 boisdevname=0 quiet elevator=noop"
+GRUB_CMDLINE_LINUX="rd.lvm.lv=centos/root rd.lvm.lv=centos/swap crashkernel=auto rhgb net.ifnames=0 boisdevname=0 quiet "
 GRUB_DISABLE_RECOVERY="true"
```

### Actual Result:
```
NoMethodError
-------------
undefined method `ends_with' for Custom resource line_delete_from_list from cookbook line
```

**Comment by MarkGibbons** [comment]
@bby-bishopclark Could you paste the line with the list you want the resource to change?

**Comment by bby-bishopclark** [comment]
Yes.  I've updated the comment to show the file contents ideally missing the 'elevator=noop' in the ^GRUB line.

**Comment by bby-bishopclark** [comment]
I suspect actually someone updated the README.md , and bulk-copied add_to_list as delete_from_list to save time/typos and didn't realize that not ALL options were present in the latter  ;-)

**Comment by MarkGibbons** [comment]
Sure.  I notice there are no tests for ends_with in delete from list. So the function probably was never implemented.  Delete and add list processing are intended to be symmetrical. I think I never cross checked the options when creating the tests. I'll take a look and see how hard it is to add the option, tests and processing if they are needed.

**Comment by MarkGibbons** [comment]
For version 2.0.0
````
delete_from_list 'delete elevator from grub' do
      path      '/etc/default/grub'
      pattern   'GRUB_CMDLINE_LINUX="'
      delim     [' ']
      entry     'elevator=noop'
 end
````

Will do what you want without the ends_with property.  Ends_with would be useful to get rid of the trailing blank between quiet and ".   I think there may be some other cases where end_with would be cleaner.  For now I think delete_from_list does what you expect.

GRUB_CMDLINE_LINUX="rd.lvm.lv=centos/root rd.lvm.lv=centos/swap crashkernel=auto rhgb net.ifnames=0 boisdevname=0 quiet "

**Comment by bby-bishopclark** [comment]
I think in my case I can work with a config exactly as you have above -- thanks for that!

I compared the code between them, and I can see where changes would need to go.  It looks daunting to my new-to-ruby eyeballs, but I'm hoping you'll keep this ticket open and accomplish it like a hero.  Any chance?

**Comment by MarkGibbons** [comment]
Sometime over the next month it might get in.  I've got a big PR  WIP to add some other asked for features that will be higher in priority.

Thanks for reporting the inconsistency in the documentation.  If you want to do a PR you could delete ends_with from the delete_from_list README table.

**Comment by MarkGibbons** [comment]
I'll take a look at this in June 2019.

**Comment by MarkGibbons** [comment]
Work is in progress on this issue
