### ISSUE TITLE
2.0.0 Issue with delete_lines - sensitive

### ISSUE THREAD

**Issue by askmike1** [sous-chefs/line#110]
### Cookbook version
2.0.0

### Chef-client version
12.21.14

### Platform Details
RHEL

### Scenario:
Trying to use delete_lines resource

### Steps to Reproduce:
Use delete_lines resource

### Expected Result:
Lines deleted from file

### Actual Result:
```
 ================================================================================
           Error executing action `edit` on resource 'delete_lines[Remove mware from sudoers]'
           ================================================================================

           ArgumentError
           -------------
           Property sensitive is not defined in class delete_lines[Remove mware from sudoers]

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/line/libraries/helper.rb:13:in `sensitive_default'
           /tmp/kitchen/cache/cookbooks/line/resources/delete_lines.rb:12:in `block in class_from_file'
```
Looks like you need to add 'properties' to the resource

**Comment by askmike1** [comment]
Looking at the changelog, I see 2.0.0 did drop support for chef12... not sure if this is an issue or not in chef13

**Comment by MarkGibbons** [comment]
What is the resource definition you are using?

**Comment by askmike1** [comment]
Ex:
```
delete_lines 'Remove mware from sudoers' do
  path '/etc/sudoers'
  pattern "^[%#].*[Ff][Cc]-[Mm][Ww][Aa][Rr][Ee].*"
end
```

**Comment by MarkGibbons** [comment]
Reproduced it on chef 12.  It works in chef 13 because sensitive is now a property of every resource (from memory didn't look it up).

**Comment by MarkGibbons** [comment]
Thanks for the report and quick response.  I'm stuck on chef 12 for large parts of my server herd so I understand the pain of cookbooks that require chef 13. As is I can't use my own work.

**Comment by MarkGibbons** [comment]
Pending merge.
