### ISSUE TITLE
New Resource: prepend_if_no_line

### ISSUE THREAD

**Issue by pwelch** [sous-chefs/line#115]
### Feature Request

Add a `prepend_if_no_line` resource. Similar to `append_if_no_line` except it will add the content before the line.

**Comment by MarkGibbons** [comment]
PR #101 handles this case.

**Comment by MarkGibbons** [comment]
@pwelch Could you clarify your request a bit?  You asked for the insert "before the line", do you mean at the start of the file if the line is not found anywhere else?

thanks,
  Mark

**Comment by pwelch** [comment]
@MarkGibbons, sorry it's been a bit since I thought of a use case for this feature.

If I'm remembering correctly, your description would be the use case.

**Comment by MarkGibbons** [comment]
Fixed by #128
