### ISSUE TITLE
rename repo to simply `line`

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/line#117]
To be like the other cookbooks in sous-chefs, we should change the name of this repo to `line`.

I can't remember all the places we'd want to change references, and how friendly github is about redirections.

Would we just want to update the link in the readme and the metadata? Anywhere else?

**Comment by Raboo** [comment]
would be less google friendly

**Comment by damacus** [comment]
I'm not sure I buy it. None of our repos are `*-cookbook`, or `chef-*`

Here's the traffic stats for it. Sadly I think you're right, weirdly everyone finds up via Google.

<img width="359" alt="screen shot 2018-08-16 at 09 40 54" src="https://user-images.githubusercontent.com/40786/44198192-a5668500-a138-11e8-90fe-03659dff350f.png">

**Comment by Raboo** [comment]
I assume googling "nginx chef" or "nginx cookbook" is different than a generic word like "line chef" or "line cookbook".
Line Chef or Line Cook are actual chef titles.

**Comment by Raboo** [comment]
Or perhaps people doing Chef(.io) stuff have their google profiles adapted so it doesn't matter. I guess if you use google in incognito it would be harder to find

**Comment by tas50** [comment]
As long as we have the subject tags and a proper description of the repo we should do fine on SEO.

**Comment by damacus** [comment]
Right I'll make a terraform or later on tonight and rename this sucker

**Comment by damacus** [comment]
PR in: 

https://github.com/sous-chefs/terraform-github-org/pull/103


https://circleci.com/gh/sous-chefs/terraform-github-org/72?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by MarkGibbons** [comment]
Looks done.

**Comment by josephholsten** [comment]
Looks like the Travis link in the readme in the published cookbook is now broken: https://supermarket.chef.io/cookbooks/line
