### ISSUE TITLE
How to push Multiple lines into a file using the line cookbook

### ISSUE THREAD

**Issue by AnishAnil** [sous-chefs/line#118]
### Cookbook version
Version 1.0

### Chef-client version
Chef Client, version 14.3.37

### Platform Details
[RHEL]

### Scenario:
UseCase:

Trying to insert multiple lines to a file without deleting the original file.

It simply does not inset anything post the first line and does not fail either.

Recipe Used:
replace_or_add "New Lines" do
    path "/etc/rsyslog.conf"
    pattern "# ### end of the forwarding rule ###"
    line "#audit log
        $ModLoad imfile"
  end

### Steps to Reproduce:
Import the line quick book into the chef Server.
Add the above lines to the recipe 
run the cookbook to add multiple lines to the config files

### Expected Result:
All the lines should have been added to the files? one line at a time and on the next lines
Ex: #audit log
        $ModLoad imfile
        $Line 2
        $Line 3
        $Line 4

### Actual Result:
Only one line is added to the file and no other lines gets added even after changing the code to include the \n character

#audit log

**Comment by MarkGibbons** [comment]
Hi @AnishAnil 


A line specified in the replace_or_add resource is not an arbitrary string.  There is a documented limitation:  "**Lines to be added should not contain EOL characters. The providers do not do multiline regex checks**."  This limitation specifically excludes the case you mention.

If you want to add a line without replacing an existing line you might use the append_if_no_line resource.  You would need to use that resource once for every line you wanted to add.

I'm going to close this issue.  The expected use is already explicitly excluded.  There's a pending PR that provides something like the requested capability.  You can also call the resources multiple times to accomplish what you want.

Mark
