### ISSUE TITLE
replace_or_add does not add line 

### ISSUE THREAD

**Issue by a13x212** [sous-chefs/line#12]
The file ifcfg-eth0 does not contain any line with the string "peerdns". The expected behavior is for it to add the line "PEERDNS=no".

   replace_or_add "Disabling PEERDNS" do
      path "/etc/sysconfig/network-scripts/ifcfg-eth0"
      pattern "PEERDNS.*"
      line "PEERDNS=no"
    end
# /etc/sysconfig/network-scripts/ifcfg-eth0

DEVICE=eth0
BOOTPROTO=static
HWADDR=ab:cd:ef:11:06:09
IPADDR=10.1.1.2
NETMASK=255.255.255.0
DEFROUTE=yes
GATEWAY= 10.1.1.1
IPV6INIT=yes
IPV6_AUTOCONF=no
IPV6ADDR=2003:5401:7119:0074:00d2:2bd2:ff11:0652/64
IPV6_DEFAULTGW=fe80::def%eth0
DNS1=10.1.1.1
DNS2=10.1.1.1
ONBOOT=yes
NM_CONTROLLED=no

**Comment by jblaine** [comment]
The code for this fix has been merged. Right now it is unreleased to the community site, but is in the master branch of this git repo.

**Comment by vills** [comment]
Guys, maybe you should release fix for this bug to community site? It was fixed about 6 month ago, but still unfixed in community site.

**Comment by jblaine** [comment]
I don't have any special privs here. @someara has to take care of that.

**Comment by someara** [comment]
pushed. sorry about that! slipped through the cracks
