### ISSUE TITLE
Cannot enable `backup`

### ISSUE THREAD

**Issue by jflemer-ndp** [sous-chefs/line#120]
### Cookbook version
2.0.2

### Chef-client version
13.2.20

### Platform Details
RHEL6

### Scenario:
Backup file in `/var/chef/backup/...`

### Steps to Reproduce:

    replace_or_add 'foo' do
      path '/etc/issue'
      pattern '^nonsense.*'
      content 'nonsense'
      backup true
    end

### Expected Result:

Edit works, find backup in `/var/chef/backup/etc/issue*`

### Actual Result:

    Chef::Exceptions::ValidationFailed
    ----------------------------------
    Property backup must be one of: Integer, false!  You passed true.

    Cookbook Trace:
    ---------------
    /var/chef/cookbooks/line/resources/replace_or_add.rb:39:in `block (2 levels) in class_from_file'
    /var/chef/cookbooks/line/resources/replace_or_add.rb:37:in `block in class_from_file'

### Suggestion:

Match the `file` resource, and use `[ Integer, FalseClass ]` for the `backup` attribute. (https://github.com/chef/chef/blob/2878c06b5287ce9415406738da7ccd3ed0ac0ebc/lib/chef/resource/file.rb#L60)

**Comment by MarkGibbons** [comment]
Should be fixed now.
