### ISSUE TITLE
Add not_if and only_if, also standard cases such as exists/not exists

### ISSUE THREAD

**Issue by mrswadge** [sous-chefs/line#131]
When using _filter_lines_ there is no way to tell it not to append a line if one already exists. There should also be ways to code custom _not_if_ and _only_if_ clauses to prevent multiple converges. These options should probably be rolled out to all the resources where appropriate.

An example of what I wanted to achieve in ruby code is as follows where it will insert after a matched line, but only if the new line is not already present in the file.

              match = /# comment to find/
              newline = 'some.property=abc123'
              ruby_block "modify #{filename} insert_line_after_match##{editIndex} file" do
                block do
                  line_count = 0
                  File.open( filepath ).each do |line|
                    if line =~ (/#{Regexp.escape(newline)}/)
                      line_count += 1
                    end
                  end
                  if line_count == 0
                    file = Chef::Util::FileEdit.new( filepath )
                    file.insert_line_after_match(match, newline)
                    file.write_file
                  end
                  action :run
                  not_if { line_count = 1 }
                end
              end

I saw that filter_lines was the only way to insert near a given line, but there is no way to tell it that should only insert the line if it is not already present, so it inserts a new line on every convergence.

            filter_lines "modify #{filename} insert_line_after_match##{editIndex} file" do
              path filepath
              filters after: [match, newline, :each]
            end

I therefore feel it would be appropriate to add not_if and only_if to the libraries, but for something that is a fairly common need such as this use case, new option switches could be added to cater for these more common use cases internally.

**Comment by MarkGibbons** [comment]
HI mrswadge,

 The sample filters are intended to be idempotent.  They are designed to do what you want to tell them to do. They should not insert a line multiple times.  Do you have an example of using filter_lines that inserts lines over and over again?

Thinking about it, this might be the case you have a problem with.

In your example above if the newline you insert matches the regex in match then every time the resource runs lines will be inserted.  Both after the original match and after the newline match.  I can make that experience safer by disallowing that case.  The replace filter (not yet published) won't let you insert lines that would be replaced for instance.


Thanks,
  Mark

**Comment by mrswadge** [comment]
Hi Mark,

I've worked out what my issue was now and I believe that it is working as intended. My action was modifying a java.security file, specifically the area below.

```
#
# Default login configuration file
#
#login.config.url.1=file:${user.home}/.java.login.config
```

I was using the following code

```
def to_regexp(value, flags=Regexp::IGNORECASE)
  return (value.instance_of? Regexp) ? value : Regexp.new("#{Regexp.escape(value)}", flags)
end

match = to_regexp('login.config.url.1')
newline = 'login.config.url.1=file:${java.home}/lib/security/Application.login.config'

filter_lines "modify #{path}/java.security" do
  path "#{path}/java.security"
  filters after: [match, newline, :last]
end
```

First time it correctly inserted the line:

```
#
# Default login configuration file
#
#login.config.url.1=file:${user.home}/.java.login.config
login.config.url.1=file:${java.home}/lib/security/Application.login.config
```

Each subsequent time it added a new line.

```
#
# Default login configuration file
#
#login.config.url.1=file:${user.home}/.java.login.config
login.config.url.1=file:${java.home}/lib/security/Application.login.config
login.config.url.1=file:${java.home}/lib/security/Application.login.config
```

To stop this, I have now changed my match to the following and this is now idempotent.

```
match = to_regexp('#login.config.url.1')
```

I will close off this issue.

Cheers,
Stuart

**Comment by MarkGibbons** [comment]
I'll probably add something to allow folks to avoid your initial situation. Repeated inserts is a really nasty thing to have happen.
