### ISSUE TITLE
Dollar Sign

### ISSUE THREAD

**Issue by RossLYoung** [sous-chefs/line#14]
I'd like to append the following 3 lines to my bashrc with the 'append_if_no_line' resource......

export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Devel
source /usr/local/bin/virtualenvwrapper.sh

However, on subsequent chef runs, the lines with dollar signs are continually appended.

**Comment by rtkmparrott** [comment]
The $ character needs to be escaped in the regular expression, but isn't. 

https://github.com/someara/line-cookbook/blob/master/libraries/default.rb#L22

This should updated to include ^ and $, and should be fine after that.

**Comment by someara** [comment]
I believe this is resolved now that $ is being escaped. Closing for now, please re-open if this is still an issue
