### ISSUE TITLE
Unknown filter error with delete_between and after filters

### ISSUE THREAD

**Issue by alissaa** [sous-chefs/line#159]
### Cookbook version
2.3.2

### Chef-client version
13.8.5

### Platform Details
Oracle Linux Server 7.4

### Scenario:
I am trying to remove multiple lines from a file and then add in a particular set of lines,

### Steps to Reproduce:
Pull down line cookbook as dependency and inside test cookbook insert the following into a recipe:

text_lines =
'              <security-domains>
                <security-domain name=\"test-domain\" cache-type=\"default\">
                  <authentication>
                    <login-module code=\"ConfiguredIdentity\" flag=\"required\">
                      <module-option name=\"username\" value=\"\"/>
                      <module-option name=\"password\" value=\"\"/>
                      <module-option name=\"principal\" value=\"\"/>
                    </login-module>
                </authentication>
              </security-domain>'

match_pattern = /.*<subsystem xmlns=\"urn:jboss:domain:security:1.2\">.*/
filter_lines 'test.xml xxx-xxx-xxx' do
  path "#{conf_path}/#{src_filepath}/#{config_file}"
  filters(
    [
      { delete_between: [/.*<security-domains>/, /.*<\/security-domains>/] },
      { after: [match_pattern, text_lines, :first] },
    ]
  )
end

### Expected Result:
I expected all lines in the xml to be deleted between <security-domains> and <\/security-domains> and then have the lines added in from above. 

### Actual Result:
kitchen converge fails with the following error: 

====================================================================
           Error executing action `edit` on resource 'filter_lines[test.xml xxx-xxx-xxx]'
           ====================================================================
           
           ArgumentError
           -------------
           Unknown filter, delete_between, specified
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/line/libraries/helper.rb:53:in `filter_method'
           /tmp/kitchen/cache/cookbooks/line/libraries/helper.rb:67:in `invoke_filter'
           /tmp/kitchen/cache/cookbooks/line/libraries/helper.rb:30:in `block in apply_filter'
           /tmp/kitchen/cache/cookbooks/line/libraries/helper.rb:29:in `each'
           /tmp/kitchen/cache/cookbooks/line/libraries/helper.rb:29:in `apply_filter'
           /tmp/kitchen/cache/cookbooks/line/resources/filter_lines.rb:55:in `block (2 levels) in class_from_file'
           /tmp/kitchen/cache/cookbooks/line/resources/filter_lines.rb:54:in `each'
           /tmp/kitchen/cache/cookbooks/line/resources/filter_lines.rb:54:in `block in class_from_file'
           
           Resource Declaration:
           ---------------------
           suppressed sensitive resource output
           
           Compiled Resource:
           ------------------
           suppressed sensitive resource output
           
           System Info:
           ------------
           chef_version=13.8.5
           platform=oracle
           platform_version=6.10
           ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
           program_name=chef-solo worker: ppid=10532;start=15:44:57;
           executable=/opt/chef/bin/chef-solo

**Comment by MarkGibbons** [comment]
Thank you for the report.  I'll take a look.

**Comment by MarkGibbons** [comment]
This looks like a problem with the resource and the helper method using the same name.  The code works on chef 14, fails on 13 and 15.  Unfortunately the code was developed on 14.  A fix is on the way.

**Comment by MarkGibbons** [comment]
Should be fixed in 2.3.3
