### ISSUE TITLE
No version 2.3.2 tag, so Chef Supermarket does not give 100% quality

### ISSUE THREAD

**Issue by apogrebnyak** [sous-chefs/line#162]
### Cookbook version
2.3.2

Go to chef supermarket, select version 2.3.2 of this cookbook

Quality meter is at 88%, and the reason is

Version Tag Metric

2.3.2 failed this metric

Failure: To pass this metric, your cookbook metadata must include a source url, the source url must be in the form of https://github.com/user/repo, and your repo must include a tag that matches this cookbook version number

All other quality metrics are fine

**Comment by JohnRoesler** [comment]
Unfortunately, even if we add the release on GitHub, I don't believe the quality metric will go to 100% unless another version is released properly. I've made this mistake before myself.

**Comment by xorima** [comment]
it's why we use `stove` to release normally, it handles the tagging for us,
once in a while we do forget though

**Comment by MarkGibbons** [comment]
Added the 2.3.3 tag to the next version.  I'll try to use stove to push to supermarket.  Stove didn't work last time.
