### ISSUE TITLE
Remove the chef 12 support code to make maintenance simpler

### ISSUE THREAD

**Issue by MarkGibbons** [sous-chefs/line#167]
### Cookbook version
Current

Remove the chef 12 support code if that makes the cookbook simpler to maintain.  The only known chef 12 method is in the helper code for the sensitive option.  Chef 12 throws an exception and we catch it.  This change would be a breaking change.

**Comment by MarkGibbons** [comment]
I still see too many folks using chef 12 so I'm waiting on implementing this change.

**Comment by damacus** [comment]
I'm looking at bumping the minimum version to 15.3 so we get unified mode and Chef 17 support. 

At some point, I feel like it's just worth dropping 12.5 support all together.

**Comment by ramereth** [comment]
I'm all for doing that at this point.

**Comment by MarkGibbons** [comment]
ok

**Comment by MarkGibbons** [comment]
Fixed by #220
