### ISSUE TITLE
Version 2.9.0 is tagged incorrectly

### ISSUE THREAD

**Issue by tilne** [sous-chefs/line#207]
## :ghost: Brief Description

2.9.0 is tagged as "2.9.0" instead of "v2.9.0". 

## :pancakes: Cookbook version

2.9.0

## :woman_cook:  Chef-Infra Version

N/A

## :tophat: Platform details

N/A

## Steps To Reproduce

```
➜  git clone https://github.com/sous-chefs/line
➜  cd line
➜  git checkout v2.9.0 
error: pathspec 'v2.9.0' did not match any file(s) known to git
```

## :heavy_plus_sign: Additional context

N/A

**Comment by MarkGibbons** [comment]
thank you for that report. That is painful.

Looks like the tag style has alternated between n.n.n and vn.n.n at random.  Probably time for some consistency.  Might not include vn.n.n though.

**Comment by MarkGibbons** [comment]
I added a v2.9.0 tag.  I think work on automating tagging is in progress.

**Comment by tilne** [comment]
> I added a v2.9.0 tag.

Thank you.

> Looks like the tag style has alternated between n.n.n and vn.n.n at random. Probably time for some consistency. Might not include vn.n.n though.

For what it's worth: of the ten supermarket cookbooks ours depends on, 9 out of 10 use the vn.n.n format. (The lone exception is this cookbook, which should maybe count as 0.5 towards that total.)

**Comment by MarkGibbons** [comment]
vN.N.N seems to be the accepted standard.
