### ISSUE TITLE
Resource add_to_list needs `provides :add_to_list` in addition to `resource_name :add_to_list` declaration

### ISSUE THREAD

**Issue by seeven-kathan** [sous-chefs/line#209]
### :speaking_head: Foreword

Resource add_to_list needs `provides :add_to_list` in addition to `resource_name :add_to_list` declaration

## :ghost: Brief Description

Since the evolution made in version 15 where provide should be specified in resource block, the cookbook need to be evolved to respect this method.

## :pancakes: Cookbook version

cookbook 'line', '~> 2.8'

## :woman_cook:  Chef-Infra Version

Chef Infra Client, version 15.13.8

## :tophat: Platform details

centos-7

## Steps To Reproduce

1. use  version 2.8.0 of the cookbook

## :heavy_plus_sign: Additional context

Compiling Cookbooks...
       [2020-08-17T09:36:48+00:00] ERROR: Deprecation CHEF-31 from /opt/chef/embedded/lib/ruby/2.6.0/forwardable.rb:230:in `setup_run_context'

         Resource add_to_list needs `provides :add_to_list` in addition to `resource_name :add_to_list` declaration

       Please see https://docs.chef.io/deprecations_resource_name_without_provides/ for further details and information on how to correct this problem.

       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/line/resources/add_to_list.rb
       ================================================================================

       Chef::Exceptions::DeprecatedFeatureError
       ----------------------------------------
       Deprecation CHEF-31 from /opt/chef/embedded/lib/ruby/2.6.0/forwardable.rb:230:in `setup_run_context'

         Resource add_to_list needs `provides :add_to_list` in addition to `resource_name :add_to_list` declaration

       Please see https://docs.chef.io/deprecations_resource_name_without_provides/ for further details and information on how to correct this problem. (raising error due to treat_deprecation_warnings_as_errors being set)

       System Info:
       ------------
       chef_version=15.13.8
       platform=centos
       platform_version=7.6.1810
       ruby=ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]
       program_name=/opt/chef/bin/chef-client
       executable=/opt/chef/bin/chef-client

       Running handlers:
       [2020-08-17T09:36:48+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2020-08-17T09:36:48+00:00] ERROR: Exception handlers complete
       Chef Infra Client failed. 0 resources updated in 07 seconds
       [2020-08-17T09:36:48+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2020-08-17T09:36:48+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2020-08-17T09:36:48+00:00] FATAL: Chef::Exceptions::DeprecatedFeatureError: Deprecation CHEF-31 from /opt/chef/embedded/lib/ruby/2.6.0/forwardable.rb:230:in `setup_run_context'

**Comment by MarkGibbons** [comment]
Please use version 2.9.0 of the cookbook. The latest version should have the fix you want.  Cheers
