### ISSUE TITLE
add_to_list[missing_file fail] on kitchen converge

### ISSUE THREAD

**Issue by ghost** [sous-chefs/line#217]
* add_to_list[missing_file fail] action edit[2020-12-11T21:20:28+00:00] ERROR: add_to_list[missing_file fail] (test::add_to_list line 170) had an error: RuntimeError: File /tmp/nofilehere not found; ignore_failure is set, continuing
       
           
           ================================================================================
           Error executing action `edit` on resource 'add_to_list[missing_file fail]'
           ================================================================================
           
           RuntimeError
           ------------
           File /tmp/nofilehere not found
           
           Cookbook Trace: (most recent call first)
           ----------------------------------------
           /tmp/kitchen/cache/cookbooks/line/libraries/helper.rb:72:in `raise_not_found'
           /tmp/kitchen/cache/cookbooks/line/resources/add_to_list.rb:14:in `block in class_from_file'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/test/recipes/add_to_list.rb
           
           170: add_to_list 'missing_file fail' do
           171:   path '/tmp/nofilehere'
           172:   pattern Regexp.escape('empty_delimited_list=(')
           173:   delim [', ', '"']
           174:   ends_with ')'
           175:   entry 'newentry'
           176:   ignore_missing false
           177:   ignore_failure true
           178: end
           179: 
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/test/recipes/add_to_list.rb:170:in `from_file'
           
           add_to_list("missing_file fail") do
             action [:edit]
             default_guard_interpreter :default
             declared_type :add_to_list
             cookbook_name "test"
             recipe_name "add_to_list"
             path "/tmp/nofilehere"
             pattern "empty_delimited_list=\\("
             delim [", ", "\""]
             entry "newentry"
             ends_with ")"
             ignore_missing false
             ignore_failure true
           end
           
           System Info:
           ------------
           chef_version=16.7.61
           platform=amazon
           platform_version=2
           ruby=ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
           program_name=/opt/chef/bin/chef-client
           executable=/opt/chef/bin/chef-client

**Comment by ramereth** [comment]
@fac3le55 can you please provide example recipe code which can replicate this?

**Comment by MarkGibbons** [comment]
Hi @fac3le55 

  That code is there to test the error condition caused by a missing file.  With a missing file and ignore_missing false the resource is supposed to throw an error.  That's the opposite of the usual behavior for add_to_list, but very much expected from that test. I'm going to close this issue.  Please send a note if I'm missing something.  I did some stuff with resource handlers to let me check the status of the failures inside the inspec tests.

thanks for using the line cookbook.

Mark

**Comment by jasonghelfman** [comment]
Hi. This was not in relation to any code I wrote. I was running a kitchen test against suite provided.

Thanks for the line cookbook!

**Comment by ghost** [comment]
Hi. This was not in relation to any code I wrote. I was running a kitchen test against suite provided.

Thanks for the line cookbook!
