### ISSUE TITLE
Chefspec coverage needed

### ISSUE THREAD

**Issue by haidangwa** [sous-chefs/line#26]
Untouched Resources:
  append_if_no_line[Operation 1]
  replace_or_add[Operation 2]
  replace_or_add[Operation 3]
  replace_or_add[Operation 4]
  delete_lines[Operation 5]
  delete_lines[Operation 6]

Also, there are no specs for add_to_list

**Comment by someara** [comment]
I've commented out that whole file... closing this for now.
