### ISSUE TITLE
replace_or_add failing on XML document

### ISSUE THREAD

**Issue by hulu1522** [sous-chefs/line#28]
I am using this resource on a machine.  It will find the line it needs on the first run and replaces it correctly.  Every run after that fails because it can't detect that the line was already replaces so it appends it to the end of the document.

CODE:

``` ruby
replace_or_add "sso crowd auth" do
  path "#{node["confluence"]["install_dir"]}/confluence/confluence/WEB-INF/classes/seraph-config.xml"
  pattern %Q[<!-- <authenticator class="com.atlassian.confluence.user.ConfluenceCrowdSSOAuthenticator"/> -->]
  line %Q[<authenticator class="com.atlassian.confluence.user.ConfluenceCrowdSSOAuthenticator"/>]
  notifies :restart, "service[#{service_name}]", :delayed
end
```

DEBUG OUTPUT:

```
* replace_or_add[sso crowd auth] action edit[2015-05-15T20:30:39+00:00] INFO: Processing replace_or_add[sso crowd auth] action edit (tcn_atlassian::confluence line 112)
[2015-05-15T20:30:39+00:00] DEBUG: providers for generic replace_or_add resource enabled on node include: []
[2015-05-15T20:30:39+00:00] DEBUG: providers that refused resource replace_or_add[sso crowd auth] were: []
[2015-05-15T20:30:39+00:00] DEBUG: providers that support resource replace_or_add[sso crowd auth] include: []
[2015-05-15T20:30:39+00:00] DEBUG: no providers supported the resource, falling back to enabled handlers
[2015-05-15T20:30:39+00:00] DEBUG: providers that survived replacement include: []
[2015-05-15T20:30:39+00:00] DEBUG: dynamic provider resolver FAILED to resolve a provider
```

Is there any reason why it is not finding the line and reporting it as "up to date"?

**Comment by someara** [comment]
"#{node[" is completeing the quote on your recipe compile

always use node['single_quotes']

-s

**Comment by hulu1522** [comment]
That was not the issue.  It compiled correctly both ways and still is not detecting the "line" portion correctly.  It finds the "pattern" just fine the first time and replaces it correctly.  On the second converge it fails to recognize that the "line" is already in the file.

Could the editor be returning some strange characters?  I'm using this on a SmartOS machine.

**Comment by someara** [comment]
There may be a bug in the regex matching library

**Comment by hulu1522** [comment]
Well then I'm confused.  Below are the two cases I'm using in the same recipe.  The first resource fails but the second one works:

``` ruby
# # BUG: There is something wrong with matching here.
replace_or_add "sso crowd auth 1" do
  path "#{node["confluence"]["install_dir"]}/confluence/confluence/WEB-INF/classes/seraph-config.xml"
  pattern '<!-- <authenticator class="com.atlassian.confluence.user.ConfluenceCrowdSSOAuthenticator"/> -->'
  line '<authenticator class="com.atlassian.confluence.user.ConfluenceCrowdSSOAuthenticator"/>'
  notifies :restart, "service[#{service_name}]", :delayed
end


replace_or_add "sso crowd auth 2" do
  path "#{node["confluence"]["install_dir"]}/confluence/confluence/WEB-INF/classes/seraph-config.xml"
  pattern '<authenticator class="com.atlassian.confluence.user.ConfluenceAuthenticator"/>'
  line '<!-- <authenticator class="com.atlassian.confluence.user.ConfluenceAuthenticator"/> -->'
  notifies :restart, "service[#{service_name}]", :delayed
end
```

Thanks for the help

**Comment by hulu1522** [comment]
@someara So i found the issue and it is a change that happened between 0.5.1 and 0.5.2 [here](https://github.com/someara/line-cookbook/commit/beb1fbad9647edb2d0101c89a7d1a35efa3e06cd)

**Comment by hulu1522** [comment]
@someara So looks like it is just a logic error on my side.  My pattern was too strict.  When your code compared the 'line' with the 'regex' it wouldn't match.  The second example works because the 'line' can be found in the 'pattern' unlike the first example.  The first example is also trying to match the `<!--` and `-->` which won't work.  That then makes it not found and the code will then append it to the file.  Sorry to bother you with this issue.

**Comment by hulu1522** [comment]
@someara I just opened PR #29 which might offer a solution for this issue.  I would guess this mistake is not isolated so the fix I propose will catch it and print a couple of warnings to notify the user to adjust their pattern.  Any thoughts would be good.  This provides a small safety net and backwards compatibly to those using line 0.5.1 or earlier.

**Comment by MarkGibbons** [comment]
@somera and @hulu1522 We ran into the behavior of line adding the same line repeatedly to the end of the file. Why should the pattern of the line to be replaced match the line being added?  I don't think that should be required.  As originally coded the pattern has to match the original line and the replacement line, that seems too restrictive.

replace_or_add
  pattern 'a'
  line  'b'

I'd expect a line matching 'a' to be replaced by line 'b' , even though 'b' doesn't match the pattern.

Hulu1522, your fix looks like it will make line behave more like what I'd expect.  I don't see any reason for the info log messages though.  We had a similar PR in the works.

Thanks

**Comment by hulu1522** [comment]
@MarkGibbons I agree with you.  I don't even care if my PR is merged as long as a fix is pushed.  I just wanted to offer a solution.  Let us know when your PR is ready.  Thanks.

**Comment by hulu1522** [comment]
@MarkGibbons I removed the comments as suggested in PR #29

**Comment by hulu1522** [comment]
:+1:
PR #30

**Comment by jarsever** [comment]
I think this issue has been resolved.  Thanks.  :)

**Comment by MarkGibbons** [comment]
Yes, PR #30 fixed the problem.
