### ISSUE TITLE
WARN: This will no longer work in Chef 13

### ISSUE THREAD

**Issue by kbaltrinic** [sous-chefs/line#32]
Not sure when this started, but some time since we started using the Chef 12 client, our usage of the Line cookbook as started to emit the following warning:

```
WARN: Class Chef::Provider::AppendIfNoLine does not declare 'resource_name :append_if_no_line'.
WARN: This will no longer work in Chef 13: you must use 'resource_name' to provide DSL.
```

We are seeing the same warning on `replace_or_add` as well.  Likely occurs elsewhere but these are the only two Line resources that we are using.

**Comment by ahrenstein** [comment]
I see this as well.
+1 to have this issue fixed before Chef 13 comes out.

**Comment by CloCkWeRX** [comment]
https://github.com/chef/chef/issues/3614
