### ISSUE TITLE
Only Replace a Line in replace_or_add

### ISSUE THREAD

**Issue by karcaw** [sous-chefs/line#38]
It would be nice if replace_or_add had an option to only replace it matched.

This could be a new LWRP, but may be easier to just add an option to replace_or_add so that if a line is not matched just move on, and not add it at the bottom.

for example:
File:

```
Line 1
Line 2
Line 3
```

This changes something:

```
replace_or_add 'file' do
   path '<file>'
  pattern 'Line 2'
  line 'Line Two'
end
```

But this takes No action:

```
replace_or_add 'file' do
   path '<file>'
  pattern 'Line 4'
  line 'Line Four'
end
```

**Comment by MarkGibbons** [comment]
I can add a replace_only option to replace_or_add  very easily.

**Comment by karcaw** [comment]
Thanks!

**Comment by someara** [comment]
merged. closing!
