### ISSUE TITLE
ReplaceOrAdd does not declare 'provides :replace_or_add'.

### ISSUE THREAD

**Issue by damacus** [sous-chefs/line#41]
```
WARN: Class Chef::Provider::ReplaceOrAdd does not declare 'provides :replace_or_add'.
This will no longer work in Chef 13: you must use 'provides' to use the resource's DSL.
```

_If_ I get a chance I will try and do some work to remove this one.

**Comment by Raboo** [comment]
@damacus did you get a chance to fix it?

**Comment by damacus** [comment]
...that would be a nope :( been busy rewriting some other stuff. @someara is it *worth* converting this to a custom resource?

**Comment by someara** [comment]
Shit I started going exactly that but forgot about it. I have a branch
somewhere that's like %75 done.

*looks*

-s

**Comment by damacus** [comment]
Alright dude feel free to kick it over. 

BTW if you haven't got time for this anymore I will shamelessly plug sous chefs :P

**Comment by Raboo** [comment]
Ok, how can I help?
Cause right now this cookbook fails with chef v13.
Perhaps @someara can push that branch and I can see if I understand enough to help out.

**Comment by damacus** [comment]
Right this is now resolved as part of the rewrite @someara can you make a release purty please?
