### ISSUE TITLE
add_to_list for lists in quotes

### ISSUE THREAD

**Issue by steflsd** [sous-chefs/line#42]
Is there any indication how add_to_list works for lists in quotes?   I am trying to append to the grub boot line options and I cant seem to figure out how to do this.

DEFAULT_APPEND="resume=/dev/sda2 splash=silent crashkernel=256M-:128M showopts"

**Comment by MarkGibbons** [comment]
@stefanlsd 

line = line.chomp + "#{new_resource.delim[0]}#{new_resource.entry}"
line = line.chomp + "#{new_resource.delim[0]}#{new_resource.entry}#{new_resource.delim[1]}"

These are the two lines that update a line in add_to_list.  Neither is going to do what you want.  That  trailing " in the DEFAULT_APPEND string will be a problem.  The code examples in the README seem to imply something should be possible, but I really don't think adding to a list with outer delimeters, the " in ="stuff more_stuff",  will work.  

Mark

**Comment by calston** [comment]
Among other things I'm not entirely sure why the regular expressions in add_to_list assert the existence of whitespace to match if an element exists or not. It's difficult to follow what the intended behaviour is at all.

**Comment by calston** [comment]
https://github.com/someara/line-cookbook/pull/43

**Comment by steflsd** [comment]
Thanks Colin. Your PR solves this issue for me.

**Comment by someara** [comment]
merged. closing!
