### ISSUE TITLE
replace_or_add multiple lines

### ISSUE THREAD

**Issue by izghitu** [sous-chefs/line#45]
Hi,

I have a file with the following contents:
```
# comment line 1
# comment line2
# comment line X
some random text
```

I want to use the replace_or_add command to make it add several lines **IF** they **DO NOT EXIST** and skip it if the lines are already there.
So I tried this:
```
replace_or_add 'blahblah' do
  path '/path/to/file'
  line 'SOMELINE 1'
  line 'SOMELINE 2'
end
```
What it did is replaced all lines from the file with **SOMELINE 2**.

Is it possible to specify multiple lines in one replace_or_add block?

THe final result I want to achieve is for it to look like below regardless of how many times it is execute:
```
# comment line 1
# comment line2
# comment line X
some random text
SOMELINE 1
SOMELINE 2
```

Please help. Thanks in advance.

**Comment by izghitu** [comment]
Ok, I was able to do it like this:
```
%w{STRING1 STRING2}.each do |i|
  replace_or_add 'blahblah' do
    path '/path/to/file'
    pattern "#{i}"
    line "#{i}"
  end
end
```
But this would work only without any special characters and empty spaces.

It would be nice to have the cookbook assume that if no pattern is specified then the pattern is the line itself and also for it to allow to use multiple line properties in one replace_or_add block.

Thanks

**Comment by damacus** [comment]
Hey @izghitu if you can make a PR to fix this we'd graciously receive it. 
However right now I'm inclined to just put this in case in the README.

**Comment by ccrebolder** [comment]
I think the append_if_no_line resource might be closer to what you're looking for?
```
%w(STRING1 STRING2).each do |i|
  append_if_no_line "add #{i}" do
    path '/path/to/file'
    line i
  end
end
```
This resource escapes the string before matching, so it doesn't matter if you have special regex characters in your string. It's important to name resources within a loop uniquely by incorporating the iterator in the name, or the resources start overwriting each other and notifications stop working.

**Comment by izghitu** [comment]
@ccrebolder thanks, this works much better

**Comment by damacus** [comment]
Thanks @ccrebolder! I'm going to go ahead and close this issue now. 

Glad this is sorted :)
