### ISSUE TITLE
delete_from_list with space delimiter does not work properly

### ISSUE THREAD

**Issue by swimfrog** [sous-chefs/line#67]
I am trying to use the line cookbook to add/remove kernel parameters from grub.conf. I tried to use delete_from_list for this, but ran into a problem.

Given the following existing file content:

```
kernel /vmlinuz-4.1.12-103.3.8.el6uek.x86_64 ro root=/dev/sda2 rd_NO_LUKS  KEYBOARDTYPE=pc KEYTABLE=us LANG=en_US.UTF-8 rd_NO_MD SYSFONT=latarcyrheb-sun16 crashkernel=auto nompath rd_NO_LVM rd_NO_DM rhgb quiet
```

And this recipe:

```
  delete_from_list "grub.conf - Remove rhgb" do
    path "/etc/grub.conf"
    pattern "^\\s*kernel .*"
    delim [' ']
    entry "rhgb"
  end

  delete_from_list "grub.conf - Remove quiet" do
    path "/etc/grub.conf"
    pattern "^\\s*kernel .*"
    delim [' ']
    entry "quiet"
  end
```

The result is:

```
kernel /vmlinuz-4.1.12-103.3.8.el6uek.x86_64 ro root=/dev/sda2 rd_NO_LUKS  KEYBOARDTYPE=pc KEYTABLE=us LANG=en_US.UTF-8 rd_NO_MD SYSFONT=latarcyrheb-sun16 crashkernel=auto nompath rd_NO_LVM rd_NO_DMquiet
```

`... rd_NO_DMquiet` -- the space delimiter gets deleted, so the second resource fails to match, and the result is malformed.

If I reverse the order of the recipe resources, it works in the test case, but I can't guarantee  the input order, so I can't really rely on that. I also tried fiddling around with the delimiter (`" "`, `"\ "`, `[" ", " "]`, etc), but no luck.

Has anyone used this to edit kernel params in grub.conf successfully? In my case, this is an oldish distro that doesn't have `grub2-mkconfig`, so I can't edit `/etc/default/grub` and then have it render the grub.cfg.

**Comment by MarkGibbons** [comment]
Taking a look.

**Comment by MarkGibbons** [comment]
Minor fix to delete_from_list would do it.
Add test case
line = line.sub(/(#{regexdelim[0]})*\s*#{new_resource.entry}(#{regexdelim[0]})*/, '')
replace with delim instead of nothing if the delimiter is \s+.
Care to submit a PR?

**Comment by MarkGibbons** [comment]
@swimfrog Thanks for finding that bug.  Master and supermarket.chef.io have been updated.
