### ISSUE TITLE
append_if_no_line doesn't work on empty files

### ISSUE THREAD

**Issue by cpressland** [sous-chefs/line#80]
When using `append_if_no_line` with an empty file the following error occurs:

```
==> docker: Error executing action `edit` on resource 'append_if_no_line[disable_cramfs_filesystem]'
==> docker:     ================================================================================
==> docker:
==> docker:     NoMethodError
==> docker:     -------------
==> docker:     undefined method `chomp' for nil:NilClass
```

Example Recipe:

```ruby
file "/etc/modprobe.d/CIS.conf" do
  content ''
  owner 'root'
  group 'root'
  mode 0644
  action :create_if_missing
end

%w(cramfs freevxfs jffs2 hfs hfsplus squashfs udf vfat).each do |fs|
  append_if_no_line "disable_#{fs}_filesystem" do
    path '/etc/modprobe.d/CIS.conf'
    line "install #{fs} /bin/true"
  end
end
```

Example workaround:

```ruby
file "/etc/modprobe.d/CIS.conf" do
  content '# CIS Benchmark Disabled Filesystems'
  owner 'root'
  group 'root'
  mode 0644
  action :create_if_missing
end

%w(cramfs freevxfs jffs2 hfs hfsplus squashfs udf vfat).each do |fs|
  append_if_no_line "disable_#{fs}_filesystem" do
    path '/etc/modprobe.d/CIS.conf'
    line "install #{fs} /bin/true"
  end
end
```

**Comment by MarkGibbons** [comment]
Thank you for the bug report.

**Comment by damacus** [comment]
Why not create the files with the content you want/need. That way you can guarantee the contents of files. 

In this case, it might even make sense just to write the file out using a template instead, as that's what it looks like you want.

**Comment by cpressland** [comment]
I could absolutely use a Template. I'm just using the `append_if_no_line` resource a lot in this recipe and stumbled upon this, figured it was worth mentioning as it caught me off guard.

**Comment by damacus** [comment]
Cool.
I'm going to close this down as "awesomely found bug". But I think/feel like it's working as designed. 

Thanks for submitting an issue!

**Comment by MarkGibbons** [comment]
It's an easy fix and could be a common edge case.  I'll code a fix.

**Comment by cpressland** [comment]
@MarkGibbons - thank you, I appreciate it.

**Comment by MarkGibbons** [comment]
Version 1.1.1 published on chef.supermarket.io with the fix.
