### ISSUE TITLE
One long string

### ISSUE THREAD

**Issue by anniehedgpeth** [sous-chefs/line#85]
When running on Windows 2012-R2-Datacenter, how do I get it to add newlines back into my file. Right now it just makes it one long string on one line, removing all the newlines.

I'm running it on Chef 12.18.31 (using it in my chef-client-updater wrapper cookbook).

**Comment by MarkGibbons** [comment]
Hi @anniehedgpeth,

   Line doesn't support windows yet.  I was looking into it this weekend but don't have anything written/ready to do that.

Mark

**Comment by damacus** [comment]
@anniehedgpeth we'd love to have a PR for this! 

If you need any help, getting started, just drop by the #sous-chefs room in the chef community slack. 

Thanks! 
Dan

**Comment by anniehedgpeth** [comment]
Oh darn, IDK how I missed that. I'll submit a PR if/when I get it working! Thanks!

**Comment by MarkGibbons** [comment]
@anniehedgpeth 

In case:  https://github.com/sous-chefs/line-cookbook/pull/87 should provide windows support for the line cookbook.  Any feed back would be wonderful.

thanks,
  Mark
