### ISSUE TITLE
Add support for windows

### ISSUE THREAD

**Issue by MarkGibbons** [sous-chefs/line#86]
Support updating files on windows servers.

**Comment by MarkGibbons** [comment]
I'm making some progress with windows support.

**Comment by josephholsten** [comment]
yay! Btw, does sous-chefs need any improvement for testing windows things? I honestly have no idea how people are doing that.

**Comment by damacus** [comment]
Yeah we do. I have some other repos that have Windows testing in them.

The Chef windows cookbook also has appveyor (windows testing) in it. 

I have an open issue on ruby_rbenv to add Windows support.it should be a copy 'n pasta when I've done it here

**Comment by MarkGibbons** [comment]
#87 was merged.  Will publish soon.
