### ISSUE TITLE
Ensure that a block of lines starting with "pattern" and ending with "pattern" contains a given block of text

### ISSUE THREAD

**Issue by MarkGibbons** [sous-chefs/line#95]
From https://tickets.opscode.com/browse/CHEF-3290.  
Start trying to implement ideas from https://github.com/chef/chef/issues/7043
Trying for a more general implementation than requested in issue #79

**Comment by damacus** [comment]
If you're at the community summit again this year We should probably get together and talk about patterns etc :+1:

**Comment by MarkGibbons** [comment]
I'll get in late  Monday.  I'll be there for the hack day on Friday.

**Comment by MarkGibbons** [comment]
Fixed by #101. Waiting review and merge. Many of the ideas and capabilities proposed by CHEF-3920 have been implemented.
