### ISSUE TITLE
Handle missing file consistently across the providers.

### ISSUE THREAD

**Issue by MarkGibbons** [sous-chefs/line#98]
I want to include this change in the 2.0.0 release.

Proposed behavior if missing file
add_to_list.rb              -> do nothing, list not found to add to
append_if_no_line.rb -> create file, add line
delete_from_list.rb     -> do nothing, list not found implies nothing to delete
delete_lines.rb            -> do nothing, line isn’t there implies nothing to delete
replace_or_add.rb      -> create file, add line

Use the ignore_missing option to allow an error to be raised in case the file is not found.  This change breaks the behavior of the recent change to add_to_list, append_if_no_line, delete_from_list,  
delete_lines.  So doing it with the other breaking changes for the 2.0.0 release makes sense to me.

**Comment by damacus** [comment]
+100 for consistent behaviour. 

I'm happy to delay the 2.0 release for this to happen.

**Comment by MarkGibbons** [comment]
fixed by #98
